apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
kubeVersion: ">= 1.13.0 < 1.17.0"
name: demo-helm-chart
version: 0.1.0
maintainers: # (optional)
  - name: Peter Nduati
    email: lnduatipeter@gmail.com
    url: https://github.com/pnduati
keywords:
- demo

