{{- if .Release.IsInstall -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "demo.name" . }}
    chart: {{ template "demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: {{ .Values.maxUnavailablePods }}
  selector:
    matchLabels:
      name: {{ include "demo.fullname" . }}
      release: {{ .Release.Name }}
{{- end -}}
